language: node_js
node_js:
  - "10.11.0"

branches:
  only:
    - master

sudo: required

addons:
  chrome: stable
  firefox: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules


script:
  - cd client
  - npm install
  - ng test --watch=false
  - npm test
  - cd ..
  - cd server
  - npm install
  - npm test
  