language: node_js
node_js:
  - "10.11.0"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - DISPLAY=:99.0

before_script:
  - yarn global add @angular/cli
  - sh -e /etc/init.d/xvfb start

cache:
  yarn: true
  directories:
    - node_modules


script:
  - cd client
  - npm install
  - ng test --watch=false
  - npm test
  - npm run lint
  - cd ..
  - cd server
  - npm install
  - npm test
  - npm run lint